
[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/comment-checker"]

[workspace.package]
version = "0.3.4"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/systemfsoftware/claude-code-comment-checker"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy.all]
level = "deny"
priority = -1

[workspace.lints.clippy.pedantic]
level = "warn"
priority = -1

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
