name: Tools

on:
  workflow_call:

permissions: {}

jobs:
  tools:
    name: tools · ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2

      - name: Shebang tools execute on this runner
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/tools/check-versions.ts
          ./scripts/tools/check-matrix.ts
